language: java
install: skip
os: linux
jdk: openjdk14
deploy:
  provider: heroku
  api_key:
    secure: KNBvBidsJJVFJ3giekgTnbKj/vXZimTmj/EGjoxhmOFxJmM1dQwT7Rmw8FBdx8i4l+Z7+yfNieQGaVGobmJHa2VDuFzCClkeJ78kDOBhZaKw3xaqlh//4FUKZE3RNmbVVZwtgAVcuO9kwew/b03e34X+ny+E8NmQX31zbJzn7knha1nXZBeWcu4cBbe3UQvSIo8cTy1PWFmJJN6XrpOwAiOhbkvpeYqHfzGfpVEgpekL4Gm812nfF3edmkvvjXIWRV/vOJs19c5dry26ULLZP6PlZrDf61UfQ6lEvgQl4bqwBn7lHTbt9v/W708AjyEvmLSONRcqjU9QQpgw/Z2IirSE+b8IpQ9s34JhcWUjR5OQRrBOvQjRgs7FrT+ibD4GaCEsZO7xwlbUKiDfhRAtcpygHWyoTOLBwybw+YmajLom27/Ji3DCNoEvJnHsQ7W9WwuDftZ/ToUCLlF6ztL87ORtMEiVHEseVr3aQoFdH/Xna766zTBpGWwPHRtKNhrxr751q2HoHPaESTExhdu+2TnrTsqrlDWm795I5lQnh6rVa9ekCuB0gLUzGnKH8e00PSJnl2GXrK6K6U0274VtiU+9hFAHyK9PWapOrGOvzODbua7LJvfmmRO8770iQQoaoVXqiyXr/ScMhuTJn2EX6pp1bPByhoZuGKwKh7ft070=
  app: turistmo
  on:
    repo: TuristMO/turistmo
addons:
  sonarcloud:
    organization: "turistmo"
    token:
      secure: "cH7ny6c10rfr/0b6mOuccFHkdw1XTr1Wuy+22GJxuUdCMJufgEVphIbUI/mO+sLk0dpf0X3JPSbbahJ7F7eW71yshR0jVN3A4DpIfyVrnyH3HmascdQcL6N4Waq24pEIKlzwMYcTDlEsk9iaz6hNDivbFMt4yv0Ee0TUFSVlqDGGgFGGmQwhuL6ctRmwtvAY5ic8viEudgKKzceCaY3iFe854crCRe5tym9JUNwmqSukBih4B+1CwglOTavn2dxAAa6kLcrdj5GFnJWqtMQ2q372KEuAUNGiixCimdte2sb5P/sIe20XTNGprVlSUGxaTldR98pftn23WQdNv16hkzbI/uCd0elfjNp038f+S2F6hOD4v1sSaTU4/58hEQLXNAls+yfs6eab0b3WJiXqrJgA818dcVll2BTt/RaQ2W2mEQ6pYRNosSH0y05Ny3LLsAkLlbZ0pX9PYhl55v/TkHdYFQFZc4b2zqG8MGlY/ULeTeS5JyuNAHnkq4DBn8oxeEGAsBXBoWpm7kWcUp2elckqPnkDFSQzeWWMGF4bShJmjSdWqYSK1oNyKXbMhSqomFaKTLWF/NZmNFV2gW0196DGuOmM9qXClwRQPjRsbp8q/m83QZvRm8UchtjxbEBklpzTJttSD+Dbdrdkc5I8GiWWnQTVg+0a9E7DaTE0P3c="
script:
  - chmod +x ./gradlew
  - "./gradlew clean build"
  - ./gradlew sonarqube
